version: '3.3'

services:

  app1:
    build: .
    env_file:
      - /opt/myapp/test/.env
    restart: always
    ports:
      - "9081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test

  app2:
    build: .
    env_file:
      - /opt/myapp/test/.env
    restart: always
    ports:
      - "9082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test
