# ===== TEST profil: PostgreSQL (test_schema) =====
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: /test

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    # Migration test_schema üzerinde çalışsın
    schemas: test_schema
    default-schema: test_schema
