version: "3.3"

services:
  socialagent-test-api:
    build: .
    container_name: socialagent-test-api

    env_file:
      - /opt/socialagent/test/.env

    environment:
      SPRING_PROFILES_ACTIVE: test

    ports:
      - "9181:8080"

    restart: unless-stopped

    networks:
      - socialagent_default