version: "3.8"

services:
  socialagent-test-api:
    build: .
    container_name: socialagent-test-api

    env_file:
      - /opt/socialagent/test/.env

    environment:
      SPRING_PROFILES_ACTIVE: test

    restart: unless-stopped

    ports:
      - "9181:8080"

    networks:
      - socialagent_default

networks:
  socialagent_default:
    external: true