version: '3.3'

services:
  socialagent-prod-api:
    build: .
    container_name: socialagent-prod-api

    env_file:
      - /opt/socialagent/prod/.env

    environment:
      SPRING_PROFILES_ACTIVE: prod

    restart: unless-stopped

    ports:
      - "9281:8080"

    networks:
      - socialagent_default

networks:
  socialagent_default:
    external: true