name: Deploy PROD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PROD VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /opt/socialagent/prod/api/socialagent/SocialAgent

            git fetch origin

            git checkout master

            git reset --hard origin/master

            chmod +x mvnw

            ./mvnw clean package -DskipTests

            docker-compose -p prod -f docker-compose.prod.yml up -d --build

            docker ps
